title = "Chris Beeley's blog"
theme = "Chris-B"
relativeURLs = true
languageCode = "en-us"
baseURL = "https://chrisbeeley.github.io/chris_beeley_blog/"
ignoreLogs = ['warning-goldmark-raw-html']


# Navigation
[menu]
 
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 3
  
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/ChrisBeeley/chris_beeley_blog"
    weight = 4